export const events = [
  {
    id: 1,
    title: "Phnom Penh Night Market Live Music",
    description: "Enjoy live band performances, street food, and local crafts.",
    category: "Music",
    location: "Phnom Penh Night Market",
    lat: 11.5746,
    lng: 104.9289,
    date: "2026-05-10",
    time: "18:00",
    agenda: "Live music, food stalls, games",
    capacity: 200,
    type: "Outdoor",
    price: "Free",
  },
  {
    id: 2,
    title: "Startup Tech Meetup",
    description: "Networking event for developers and startup founders.",
    category: "Technology",
    location: "Factory Phnom Penh",
    lat: 11.54,
    lng: 104.886,
    date: "2026-05-15",
    time: "09:00",
    agenda: "Talks, networking, workshops",
    capacity: 100,
    type: "Indoor",
    price: "$5",
  },
  {
    id: 3,
    title: "Beach Yoga Session",
    description: "Morning yoga session by the sea.",
    category: "Health",
    location: "Otres Beach, Sihanoukville",
    lat: 10.5797,
    lng: 103.5669,
    date: "2026-05-20",
    time: "06:30",
    agenda: "Yoga + meditation",
    capacity: 50,
    type: "Outdoor",
    price: "$3",
  },
];
